/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Kanban Board API
 * API для управления канбан-досками (Trello-клон)
 * OpenAPI spec version: 1.0
 */
import type {
  BoardResponseDto,
  CardResponseDto,
  CreateBoardDto,
  CreateCardDto,
  CreateColumnDto,
  LoginDto,
  LoginResponseDto,
  MoveCardDto,
  RegisterDto,
  RegisterResponseDto,
  UpdateBoardDto,
  UpdateCardDto,
} from './api.schemas'

import { customInstance } from './custom-instance'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Регистрация нового пользователя
 */
export const authControllerRegister = (
  registerDto: RegisterDto,
  options?: SecondParameter<typeof customInstance<RegisterResponseDto>>
) => {
  return customInstance<RegisterResponseDto>(
    {
      url: `/api/auth/register`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: registerDto,
    },
    options
  )
}

/**
 * @summary Логин пользователя
 */
export const authControllerLogin = (
  loginDto: LoginDto,
  options?: SecondParameter<typeof customInstance<LoginResponseDto>>
) => {
  return customInstance<LoginResponseDto>(
    {
      url: `/api/auth/login`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: loginDto,
    },
    options
  )
}

/**
 * @summary Создать новую доску
 */
export const boardsControllerCreate = (
  createBoardDto: CreateBoardDto,
  options?: SecondParameter<typeof customInstance<BoardResponseDto>>
) => {
  return customInstance<BoardResponseDto>(
    {
      url: `/api/boards`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createBoardDto,
    },
    options
  )
}

/**
 * @summary Получить все доски пользователя
 */
export const boardsControllerFindAll = (
  options?: SecondParameter<typeof customInstance<void>>
) => {
  return customInstance<void>({ url: `/api/boards`, method: 'GET' }, options)
}

/**
 * @summary Получить одну доску по id
 */
export const boardsControllerFindOne = (
  boardId: string,
  options?: SecondParameter<typeof customInstance<void>>
) => {
  return customInstance<void>(
    { url: `/api/boards/${boardId}`, method: 'GET' },
    options
  )
}

/**
 * @summary Обновить доску
 */
export const boardsControllerUpdate = (
  boardId: string,
  updateBoardDto: UpdateBoardDto,
  options?: SecondParameter<typeof customInstance<void>>
) => {
  return customInstance<void>(
    {
      url: `/api/boards/${boardId}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: updateBoardDto,
    },
    options
  )
}

/**
 * @summary Удалить доску
 */
export const boardsControllerDelete = (
  boardId: string,
  options?: SecondParameter<typeof customInstance<void>>
) => {
  return customInstance<void>(
    { url: `/api/boards/${boardId}`, method: 'DELETE' },
    options
  )
}

export const columnsControllerCreate = (
  createColumnDto: CreateColumnDto,
  options?: SecondParameter<typeof customInstance<void>>
) => {
  return customInstance<void>(
    {
      url: `/api/columns`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createColumnDto,
    },
    options
  )
}

export const columnsControllerGetByBoard = (
  boardId: string,
  options?: SecondParameter<typeof customInstance<void>>
) => {
  return customInstance<void>(
    { url: `/api/columns/board/${boardId}`, method: 'GET' },
    options
  )
}

export const columnsControllerGetOne = (
  columnId: string,
  options?: SecondParameter<typeof customInstance<void>>
) => {
  return customInstance<void>(
    { url: `/api/columns/${columnId}`, method: 'GET' },
    options
  )
}

export const columnsControllerUpdate = (
  columnId: string,
  createColumnDto: CreateColumnDto,
  options?: SecondParameter<typeof customInstance<void>>
) => {
  return customInstance<void>(
    {
      url: `/api/columns/${columnId}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: createColumnDto,
    },
    options
  )
}

export const columnsControllerDelete = (
  columnId: string,
  options?: SecondParameter<typeof customInstance<void>>
) => {
  return customInstance<void>(
    { url: `/api/columns/${columnId}`, method: 'DELETE' },
    options
  )
}

/**
 * @summary Создать новую карточку
 */
export const cardsControllerCreate = (
  createCardDto: CreateCardDto,
  options?: SecondParameter<typeof customInstance<CardResponseDto>>
) => {
  return customInstance<CardResponseDto>(
    {
      url: `/api/cards`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createCardDto,
    },
    options
  )
}

/**
 * @summary Получить все карточки колонки
 */
export const cardsControllerGetByColumn = (
  columnId: string,
  options?: SecondParameter<typeof customInstance<void>>
) => {
  return customInstance<void>(
    { url: `/api/cards/column/${columnId}`, method: 'GET' },
    options
  )
}

/**
 * @summary Получить карточку по id
 */
export const cardsControllerFindOne = (
  cardId: string,
  options?: SecondParameter<typeof customInstance<void>>
) => {
  return customInstance<void>(
    { url: `/api/cards/${cardId}`, method: 'GET' },
    options
  )
}

/**
 * @summary Обновить карточку
 */
export const cardsControllerUpdate = (
  cardId: string,
  updateCardDto: UpdateCardDto,
  options?: SecondParameter<typeof customInstance<void>>
) => {
  return customInstance<void>(
    {
      url: `/api/cards/${cardId}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: updateCardDto,
    },
    options
  )
}

/**
 * @summary Удалить карточку
 */
export const cardsControllerDelete = (
  cardId: string,
  options?: SecondParameter<typeof customInstance<void>>
) => {
  return customInstance<void>(
    { url: `/api/cards/${cardId}`, method: 'DELETE' },
    options
  )
}

/**
 * @summary Переместить карточку
 */
export const cardsControllerMove = (
  cardId: string,
  moveCardDto: MoveCardDto,
  options?: SecondParameter<typeof customInstance<void>>
) => {
  return customInstance<void>(
    {
      url: `/api/cards/${cardId}/move`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: moveCardDto,
    },
    options
  )
}

export type AuthControllerRegisterResult = NonNullable<
  Awaited<ReturnType<typeof authControllerRegister>>
>
export type AuthControllerLoginResult = NonNullable<
  Awaited<ReturnType<typeof authControllerLogin>>
>
export type BoardsControllerCreateResult = NonNullable<
  Awaited<ReturnType<typeof boardsControllerCreate>>
>
export type BoardsControllerFindAllResult = NonNullable<
  Awaited<ReturnType<typeof boardsControllerFindAll>>
>
export type BoardsControllerFindOneResult = NonNullable<
  Awaited<ReturnType<typeof boardsControllerFindOne>>
>
export type BoardsControllerUpdateResult = NonNullable<
  Awaited<ReturnType<typeof boardsControllerUpdate>>
>
export type BoardsControllerDeleteResult = NonNullable<
  Awaited<ReturnType<typeof boardsControllerDelete>>
>
export type ColumnsControllerCreateResult = NonNullable<
  Awaited<ReturnType<typeof columnsControllerCreate>>
>
export type ColumnsControllerGetByBoardResult = NonNullable<
  Awaited<ReturnType<typeof columnsControllerGetByBoard>>
>
export type ColumnsControllerGetOneResult = NonNullable<
  Awaited<ReturnType<typeof columnsControllerGetOne>>
>
export type ColumnsControllerUpdateResult = NonNullable<
  Awaited<ReturnType<typeof columnsControllerUpdate>>
>
export type ColumnsControllerDeleteResult = NonNullable<
  Awaited<ReturnType<typeof columnsControllerDelete>>
>
export type CardsControllerCreateResult = NonNullable<
  Awaited<ReturnType<typeof cardsControllerCreate>>
>
export type CardsControllerGetByColumnResult = NonNullable<
  Awaited<ReturnType<typeof cardsControllerGetByColumn>>
>
export type CardsControllerFindOneResult = NonNullable<
  Awaited<ReturnType<typeof cardsControllerFindOne>>
>
export type CardsControllerUpdateResult = NonNullable<
  Awaited<ReturnType<typeof cardsControllerUpdate>>
>
export type CardsControllerDeleteResult = NonNullable<
  Awaited<ReturnType<typeof cardsControllerDelete>>
>
export type CardsControllerMoveResult = NonNullable<
  Awaited<ReturnType<typeof cardsControllerMove>>
>
