/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Kanban Board API
 * API для управления канбан-досками (Trello-клон)
 * OpenAPI spec version: 1.0
 */
export interface RegisterDto {
  /** Email пользователя */
  email: string;
  /** Пароль (мин. 6 символов) */
  password: string;
}

export interface RegisterResponseDto {
  uuid: string;
  email: string;
}

export interface LoginDto {
  email: string;
  password: string;
}

export interface LoginResponseDto {
  access_token: string;
}

export interface CreateBoardDto {
  /** Название доски */
  title: string;
}

export interface BoardResponseDto {
  uuid: string;
  title: string;
  userId: string;
  createdAt: string;
  updatedAt: string;
}

export interface UpdateBoardDto {
  title: string;
}

export interface CreateColumnDto {
  title: string;
  boardId: string;
}

export interface CreateCardDto {
  title: string;
  description?: string;
  columnId: string;
}

/**
 * @nullable
 */
export type CardResponseDtoDescription = { [key: string]: unknown } | null;

export interface CardResponseDto {
  uuid: string;
  title: string;
  /** @nullable */
  description: CardResponseDtoDescription;
  columnId: string;
  position: number;
  createdAt: string;
  updatedAt: string;
}

export interface UpdateCardDto {
  title: string;
  description?: string;
}

export interface MoveCardDto {
  targetColumnId: string;
  newPosition: number;
}

